#!/bin/bash

#Colors:
        Rd='\033[0;31m'    # Red
        Gn='\033[0;32m'  # Green
        Yw='\033[0;33m' # Yellow
        Be='\033[0;34m'   # Blue
        Pe='\033[0;35m' # Purple
        We='\033[0;97m'  # White

echo -e "$We
  ╪════════════════════════════════════════════════════════════════════════╪$Rd  

      ██████╗██╗  ██╗ █████╗  ██████╗ █████╗ ██╗          ██████╗██████╗ 
     ██╔════╝██║  ██║██╔══██╗██╔════╝██╔══██╗██║         ██╔════╝╚════██╗
     ██║     ███████║███████║██║     ███████║██║         ██║      █████╔╝
     ██║     ██╔══██║██╔══██║██║     ██╔══██║██║         ██║     ██╔═══╝ 
     ╚██████╗██║  ██║██║  ██║╚██████╗██║  ██║███████╗    ╚██████╗███████╗
      ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚══════╝     ╚═════╝╚══════╝$We
                            
                          $Pe——==[[乃ㄚ 卄0尺ㄩ]]==——$We       

  ╪════════════════════════════════════════════════════════════════════════╪" 


gen_id() {
    local id=$(cat /dev/urandom | tr -dc 'a-z0-9' | fold -w 10 | head -n 1)
    echo "$id"
}

addtarget() {
    echo -e "
    $Be ADD your SSH connection $We
    "   
    read -p "> Username: " userssh
    read -p "> Password: " passwdssh
    read -p "> IP: " ipssh
    read -p "> Port: " portssh
    echo -e "$(gen_id) $userssh $passwdssh $ipssh:$portssh" >> ~/.sith/chacal-c2/targets.txt
    echo
    echo -e "$Gn Added $We"
    echo
    echo
    clear
}

accesstarget() {
    echo -e "
    $Pe Acess SSH connection $We
    "
    credentials_file="~/.sith/chacal-c2/targets.txt"
    read -p "> Target ID: " targetid
    echo
    local line=$(grep "^$targetid" "$credentials_file")
    local user=$(echo "$line" | cut -d ' ' -f 2)
    local pass=$(echo "$line" | cut -d ' ' -f 3)
    local ip=$(echo "$line" | cut -d ' ' -f 4 |cut -d ':' -f 1)
    local port=$(echo "$line" | cut -d ' ' -f 4 |cut -d ':' -f 2)
    echo -e "$Gn Target password:$We $pass" 
    ssh $user@$ip -p $port
}

removetarget() {
    echo -e "
    $Rd Remove SSH connection $We
    "
    read -p "> Target ID: " targetid
    sed -i "/$targetid/d" ~/.sith/chacal-c2/targets.txt
    echo
    echo
    clear
}

logs=$(cat ~/.sith/chacal-c2/targets.txt | sed -E 's/ / : /g' | sed 's/^/ /')
    echo -e "
   
   [$Yw?$We]════════════════════════════════════════════════╗
   ║  Chacal-C2 Directory: $Gn~/.sith/chacal-c2$We          ║ 
   ║  Targets File: $Gn~/.sith/chacal-c2/targets.txt$We     ║ 
   ╚══════════════════════════════════════════════════╝ 
 
 ═══════════╪════════════╪══════════════╪═══════════════
 $Pe     ID    $We│$Pe    User    $We│$Pe    Passwd    $We│$Pe    Address$We           
 ═══════════╪════════════╪══════════════╪═══════════════
    "
    cat ~/.sith/chacal-c2/targets.txt | sed -E 's/ /   :   /g' | sed 's/^/ /'

    echo -e "
    
    1. Return
    2. Add Target
    3. Remove Target
    4. Access Target
    "
    read -p "[Option]> " option

    case $option in
      1)
        exit
        ;;
      2)
        addtarget
        ;;
      3)
        removetarget
        ;;
      4)
        accesstarget
        ;;
      *)
        echo
        echo -e "$Rd"  Invalid Option!"$We"
        echo
        read -p " Press any key to continue..."
        ;;
esac
